[project]
name = "citycoins-protocol"
authors = []
description = ""
telemetry = false
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

# MAINNET REQUIREMENTS

[[project.requirements]]
contract_id = "SP000000000000000000002Q6VF78.pox"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[[project.requirements]]
contract_id = "SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.citycoin-core-v2-trait"

[[project.requirements]]
contract_id = "SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.citycoin-vrf-v2"

[[project.requirements]]
contract_id = "SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-auth-v2"

[[project.requirements]]
contract_id = "SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-core-v2"

[[project.requirements]]
contract_id = "SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-token-v2"

[[project.requirements]]
contract_id = "SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.newyorkcitycoin-auth-v2"

[[project.requirements]]
contract_id = "SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.newyorkcitycoin-core-v2"

[[project.requirements]]
contract_id = "SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.newyorkcitycoin-token-v2"

# TESTNET REQUIREMENTS

[[project.requirements]]
contract_id = "ST000000000000000000002AMW42H.pox"

[[project.requirements]]
contract_id = "ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard"

[[project.requirements]]
contract_id = "ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.nft-trait"

[[project.requirements]]
contract_id = "ST1XQXW9JNQ1W4A7PYTN3HCHPEY7SHM6KPA085ES6.citycoin-core-v2-trait"

[[project.requirements]]
contract_id = "ST1XQXW9JNQ1W4A7PYTN3HCHPEY7SHM6KPA085ES6.citycoin-vrf-v2"

[[project.requirements]]
contract_id = "ST1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8WRH7C6H.miamicoin-auth-v2"

[[project.requirements]]
contract_id = "ST1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8WRH7C6H.miamicoin-core-v2"

[[project.requirements]]
contract_id = "ST1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8WRH7C6H.miamicoin-token-v2"

[[project.requirements]]
contract_id = "STSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1D64KKHQ.newyorkcitycoin-auth-v2"

[[project.requirements]]
contract_id = "STSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1D64KKHQ.newyorkcitycoin-core-v2"

[[project.requirements]]
contract_id = "STSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1D64KKHQ.newyorkcitycoin-token-v2"

# CITYCOINS PROTOCOL CONTRACTS

[contracts.base-dao]
path = "contracts/base-dao.clar"

[contracts.ccd001-direct-execute]
path = "contracts/extensions/ccd001-direct-execute.clar"

[contracts.ccd002-treasury-mia-mining]
path = "contracts/extensions/ccd002-treasury.clar"

[contracts.ccd002-treasury-mia-stacking]
path = "contracts/extensions/ccd002-treasury.clar"

[contracts.ccd002-treasury-nyc-mining]
path = "contracts/extensions/ccd002-treasury.clar"

[contracts.ccd002-treasury-nyc-stacking]
path = "contracts/extensions/ccd002-treasury.clar"

[contracts.ccd003-user-registry]
path = "contracts/extensions/ccd003-user-registry.clar"

[contracts.ccd004-city-registry]
path = "contracts/extensions/ccd004-city-registry.clar"

[contracts.ccd005-city-data]
path = "contracts/extensions/ccd005-city-data.clar"

[contracts.ccd006-citycoin-mining]
path = "contracts/extensions/ccd006-citycoin-mining.clar"

[contracts.ccd007-citycoin-stacking]
path = "contracts/extensions/ccd007-citycoin-stacking.clar"

[contracts.ccd008-city-activation]
path = "contracts/extensions/ccd008-city-activation.clar"

[contracts.ccd009-auth-v2-adapter]
path = "contracts/extensions/ccd009-auth-v2-adapter.clar"

[contracts.ccd010-core-v2-adapter]
path = "contracts/extensions/ccd010-core-v2-adapter.clar"

[contracts.ccd011-stacking-payouts]
path = "contracts/extensions/ccd011-stacking-payouts.clar"

[contracts.ccip012-bootstrap]
path = "contracts/proposals/ccip012-bootstrap.clar"

[contracts.ccip013-migration]
path = "contracts/proposals/ccip013-migration.clar"

[contracts.ccip013-activation]
path = "contracts/proposals/ccip013-activation.clar"

# CITYCOINS PROTOCOL TRAITS

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"

[contracts.stacking-trait]
path = "contracts/traits/stacking-trait.clar"

[contracts.ccd002-trait]
path = "contracts/traits/ccd002-trait.clar"

[contracts.ccd006-trait]
path = "contracts/traits/ccd006-trait.clar"

[contracts.ccd007-trait]
path = "contracts/traits/ccd007-trait.clar"

# CITYCOINS EXTERNAL CONTRACTS

[contracts.citycoin-vrf-v2]
path = "tests/contracts/external/citycoin-vrf-v2.clar"

[contracts.test-ccext-governance-token-mia]
path = "tests/contracts/external/test-ccext-governance-token-mia.clar"

[contracts.test-ccext-governance-token-nyc]
path = "tests/contracts/external/test-ccext-governance-token-nyc.clar"

[contracts.test-ccext-nft-mia]
path = "tests/contracts/external/test-ccext-nft-mia.clar"

[contracts.test-ccext-nft-nyc]
path = "tests/contracts/external/test-ccext-nft-nyc.clar"

# CITYCOINS TEST PROPOSALS

[contracts.test-ccd001-direct-execute-001]
path = "tests/contracts/proposals/test-ccd001-direct-execute-001.clar"

[contracts.test-ccd001-direct-execute-002]
path = "tests/contracts/proposals/test-ccd001-direct-execute-002.clar"

[contracts.test-ccd001-direct-execute-003]
path = "tests/contracts/proposals/test-ccd001-direct-execute-003.clar"

[contracts.test-ccd002-treasury-001]
path = "tests/contracts/proposals/test-ccd002-treasury-001.clar"

[contracts.test-ccd002-treasury-002]
path = "tests/contracts/proposals/test-ccd002-treasury-002.clar"

[contracts.test-ccd002-treasury-003]
path = "tests/contracts/proposals/test-ccd002-treasury-003.clar"

[contracts.test-ccd002-treasury-004]
path = "tests/contracts/proposals/test-ccd002-treasury-004.clar"

[contracts.test-ccd002-treasury-005]
path = "tests/contracts/proposals/test-ccd002-treasury-005.clar"

[contracts.test-ccd002-treasury-006]
path = "tests/contracts/proposals/test-ccd002-treasury-006.clar"

[contracts.test-ccd002-treasury-007]
path = "tests/contracts/proposals/test-ccd002-treasury-007.clar"

[contracts.test-ccd002-treasury-008]
path = "tests/contracts/proposals/test-ccd002-treasury-008.clar"

[contracts.test-ccd002-treasury-009]
path = "tests/contracts/proposals/test-ccd002-treasury-009.clar"

[contracts.test-ccd002-treasury-010]
path = "tests/contracts/proposals/test-ccd002-treasury-010.clar"

[contracts.test-ccd002-treasury-011]
path = "tests/contracts/proposals/test-ccd002-treasury-011.clar"

[contracts.test-ccd002-treasury-012]
path = "tests/contracts/proposals/test-ccd002-treasury-012.clar"

[contracts.test-ccd003-user-registry-001]
path = "tests/contracts/proposals/test-ccd003-user-registry-001.clar"

[contracts.test-ccd003-user-registry-002]
path = "tests/contracts/proposals/test-ccd003-user-registry-002.clar"

[contracts.test-ccd003-user-registry-003]
path = "tests/contracts/proposals/test-ccd003-user-registry-003.clar"

[contracts.test-ccd004-city-registry-001]
path = "tests/contracts/proposals/test-ccd004-city-registry-001.clar"

[contracts.test-ccd004-city-registry-002]
path = "tests/contracts/proposals/test-ccd004-city-registry-002.clar"

[contracts.test-ccd005-city-data-001]
path = "tests/contracts/proposals/test-ccd005-city-data-001.clar"

[contracts.test-ccd005-city-data-002]
path = "tests/contracts/proposals/test-ccd005-city-data-002.clar"

[contracts.test-ccd005-city-data-003]
path = "tests/contracts/proposals/test-ccd005-city-data-003.clar"

[contracts.test-ccd005-city-data-004]
path = "tests/contracts/proposals/test-ccd005-city-data-004.clar"

[contracts.test-ccd005-city-data-005]
path = "tests/contracts/proposals/test-ccd005-city-data-005.clar"

[contracts.test-ccd005-city-data-006]
path = "tests/contracts/proposals/test-ccd005-city-data-006.clar"

[contracts.test-ccd005-city-data-007]
path = "tests/contracts/proposals/test-ccd005-city-data-007.clar"

[contracts.test-ccd005-city-data-008]
path = "tests/contracts/proposals/test-ccd005-city-data-008.clar"

[contracts.test-ccd005-city-data-009]
path = "tests/contracts/proposals/test-ccd005-city-data-009.clar"

[contracts.test-ccd005-city-data-010]
path = "tests/contracts/proposals/test-ccd005-city-data-010.clar"

[contracts.test-ccd005-city-data-011]
path = "tests/contracts/proposals/test-ccd005-city-data-011.clar"

[contracts.test-ccd005-city-data-012]
path = "tests/contracts/proposals/test-ccd005-city-data-012.clar"

[contracts.test-ccd005-city-data-013]
path = "tests/contracts/proposals/test-ccd005-city-data-013.clar"

[contracts.test-ccd005-city-data-014]
path = "tests/contracts/proposals/test-ccd005-city-data-014.clar"

[contracts.test-ccd005-city-data-015]
path = "tests/contracts/proposals/test-ccd005-city-data-015.clar"

[contracts.test-ccd005-city-data-016]
path = "tests/contracts/proposals/test-ccd005-city-data-016.clar"

[contracts.test-ccd005-city-data-017]
path = "tests/contracts/proposals/test-ccd005-city-data-017.clar"

[contracts.test-ccd005-city-data-018]
path = "tests/contracts/proposals/test-ccd005-city-data-018.clar"

[contracts.test-ccd005-city-data-019]
path = "tests/contracts/proposals/test-ccd005-city-data-019.clar"

[contracts.test-ccd006-citycoin-mining-001]
path = "tests/contracts/proposals/test-ccd006-citycoin-mining-001.clar"

[contracts.test-ccd006-citycoin-mining-002]
path = "tests/contracts/proposals/test-ccd006-citycoin-mining-002.clar"

[contracts.test-ccd006-citycoin-mining-003]
path = "tests/contracts/proposals/test-ccd006-citycoin-mining-003.clar"

[contracts.test-ccd006-citycoin-mining-004]
path = "tests/contracts/proposals/test-ccd006-citycoin-mining-004.clar"

[contracts.test-ccd006-citycoin-mining-005]
path = "tests/contracts/proposals/test-ccd006-citycoin-mining-005.clar"

[contracts.test-ccd007-citycoin-stacking-001]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-001.clar"

[contracts.test-ccd007-citycoin-stacking-002]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-002.clar"

[contracts.test-ccd007-citycoin-stacking-003]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-003.clar"

[contracts.test-ccd007-citycoin-stacking-004]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-004.clar"

[contracts.test-ccd007-citycoin-stacking-005]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-005.clar"

[contracts.test-ccd007-citycoin-stacking-006]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-006.clar"

[contracts.test-ccd007-citycoin-stacking-007]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-007.clar"

[contracts.test-ccd007-citycoin-stacking-008]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-008.clar"

[contracts.test-ccd007-citycoin-stacking-009]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-009.clar"

[contracts.test-ccd007-citycoin-stacking-010]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-010.clar"

[contracts.test-ccd007-citycoin-stacking-011]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-011.clar"

[contracts.test-ccd007-citycoin-stacking-012]
path = "tests/contracts/proposals/test-ccd007-citycoin-stacking-012.clar"

[contracts.test-ccd011-stacking-payouts-001]
path = "tests/contracts/proposals/test-ccd011-stacking-payouts-001.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = true
